id = "frame"
name = "Frame"
version = "0.0.1"
schema_version = 1
authors = ["ThatOneToast"]
description = "Language support for the Frame CSS DSL."
repository = "https://github.com/ThatOneToast/frame"

[grammars.frame]
repository = "https://github.com/ThatOneToast/frame"
rev = "main"
path = "editors/zed/tree-sitter-frame"

[language_servers.frame-lsp]
name = "Frame LSP"
languages = ["Frame"]
