/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 30
#define LARGE_STATE_COUNT 12
#define SYMBOL_COUNT 55
#define ALIAS_COUNT 0
#define TOKEN_COUNT 42
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 4
#define MAX_ALIAS_SEQUENCE_LENGTH 3
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 7
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_identifier = 1,
  anon_sym_LBRACE = 2,
  anon_sym_RBRACE = 3,
  anon_sym_tokens = 4,
  anon_sym_grid = 5,
  anon_sym_area = 6,
  anon_sym_card = 7,
  anon_sym_stack = 8,
  anon_sym_row = 9,
  anon_sym_button = 10,
  anon_sym_text = 11,
  anon_sym_hover = 12,
  anon_sym_focus = 13,
  anon_sym_active = 14,
  anon_sym_columns = 15,
  anon_sym_rows = 16,
  anon_sym_gap = 17,
  anon_sym_height = 18,
  anon_sym_width = 19,
  anon_sym_surface = 20,
  anon_sym_background = 21,
  anon_sym_theme = 22,
  anon_sym_padding = 23,
  anon_sym_margin = 24,
  anon_sym_radius = 25,
  anon_sym_border = 26,
  anon_sym_shadow = 27,
  anon_sym_place = 28,
  anon_sym_in = 29,
  anon_sym_col = 30,
  anon_sym_span = 31,
  anon_sym_lift = 32,
  anon_sym_glow = 33,
  anon_sym_brighten = 34,
  anon_sym_dim = 35,
  anon_sym_blur = 36,
  anon_sym_press = 37,
  anon_sym_ring = 38,
  anon_sym_smooth = 39,
  sym_comment = 40,
  sym__newline = 41,
  sym_source_file = 42,
  sym_declaration = 43,
  sym_block = 44,
  sym_state_block = 45,
  sym_statement = 46,
  sym_declaration_name = 47,
  sym_declaration_keyword = 48,
  sym_state_keyword = 49,
  sym_property_keyword = 50,
  sym_effect_keyword = 51,
  aux_sym_source_file_repeat1 = 52,
  aux_sym_block_repeat1 = 53,
  aux_sym_statement_repeat1 = 54,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_tokens] = "tokens",
  [anon_sym_grid] = "grid",
  [anon_sym_area] = "area",
  [anon_sym_card] = "card",
  [anon_sym_stack] = "stack",
  [anon_sym_row] = "row",
  [anon_sym_button] = "button",
  [anon_sym_text] = "text",
  [anon_sym_hover] = "hover",
  [anon_sym_focus] = "focus",
  [anon_sym_active] = "active",
  [anon_sym_columns] = "columns",
  [anon_sym_rows] = "rows",
  [anon_sym_gap] = "gap",
  [anon_sym_height] = "height",
  [anon_sym_width] = "width",
  [anon_sym_surface] = "surface",
  [anon_sym_background] = "background",
  [anon_sym_theme] = "theme",
  [anon_sym_padding] = "padding",
  [anon_sym_margin] = "margin",
  [anon_sym_radius] = "radius",
  [anon_sym_border] = "border",
  [anon_sym_shadow] = "shadow",
  [anon_sym_place] = "place",
  [anon_sym_in] = "in",
  [anon_sym_col] = "col",
  [anon_sym_span] = "span",
  [anon_sym_lift] = "lift",
  [anon_sym_glow] = "glow",
  [anon_sym_brighten] = "brighten",
  [anon_sym_dim] = "dim",
  [anon_sym_blur] = "blur",
  [anon_sym_press] = "press",
  [anon_sym_ring] = "ring",
  [anon_sym_smooth] = "smooth",
  [sym_comment] = "comment",
  [sym__newline] = "_newline",
  [sym_source_file] = "source_file",
  [sym_declaration] = "declaration",
  [sym_block] = "block",
  [sym_state_block] = "state_block",
  [sym_statement] = "statement",
  [sym_declaration_name] = "declaration_name",
  [sym_declaration_keyword] = "declaration_keyword",
  [sym_state_keyword] = "state_keyword",
  [sym_property_keyword] = "property_keyword",
  [sym_effect_keyword] = "effect_keyword",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_block_repeat1] = "block_repeat1",
  [aux_sym_statement_repeat1] = "statement_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_tokens] = anon_sym_tokens,
  [anon_sym_grid] = anon_sym_grid,
  [anon_sym_area] = anon_sym_area,
  [anon_sym_card] = anon_sym_card,
  [anon_sym_stack] = anon_sym_stack,
  [anon_sym_row] = anon_sym_row,
  [anon_sym_button] = anon_sym_button,
  [anon_sym_text] = anon_sym_text,
  [anon_sym_hover] = anon_sym_hover,
  [anon_sym_focus] = anon_sym_focus,
  [anon_sym_active] = anon_sym_active,
  [anon_sym_columns] = anon_sym_columns,
  [anon_sym_rows] = anon_sym_rows,
  [anon_sym_gap] = anon_sym_gap,
  [anon_sym_height] = anon_sym_height,
  [anon_sym_width] = anon_sym_width,
  [anon_sym_surface] = anon_sym_surface,
  [anon_sym_background] = anon_sym_background,
  [anon_sym_theme] = anon_sym_theme,
  [anon_sym_padding] = anon_sym_padding,
  [anon_sym_margin] = anon_sym_margin,
  [anon_sym_radius] = anon_sym_radius,
  [anon_sym_border] = anon_sym_border,
  [anon_sym_shadow] = anon_sym_shadow,
  [anon_sym_place] = anon_sym_place,
  [anon_sym_in] = anon_sym_in,
  [anon_sym_col] = anon_sym_col,
  [anon_sym_span] = anon_sym_span,
  [anon_sym_lift] = anon_sym_lift,
  [anon_sym_glow] = anon_sym_glow,
  [anon_sym_brighten] = anon_sym_brighten,
  [anon_sym_dim] = anon_sym_dim,
  [anon_sym_blur] = anon_sym_blur,
  [anon_sym_press] = anon_sym_press,
  [anon_sym_ring] = anon_sym_ring,
  [anon_sym_smooth] = anon_sym_smooth,
  [sym_comment] = sym_comment,
  [sym__newline] = sym__newline,
  [sym_source_file] = sym_source_file,
  [sym_declaration] = sym_declaration,
  [sym_block] = sym_block,
  [sym_state_block] = sym_state_block,
  [sym_statement] = sym_statement,
  [sym_declaration_name] = sym_declaration_name,
  [sym_declaration_keyword] = sym_declaration_keyword,
  [sym_state_keyword] = sym_state_keyword,
  [sym_property_keyword] = sym_property_keyword,
  [sym_effect_keyword] = sym_effect_keyword,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_block_repeat1] = aux_sym_block_repeat1,
  [aux_sym_statement_repeat1] = aux_sym_statement_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_tokens] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_grid] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_area] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_card] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_stack] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_row] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_button] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_text] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_hover] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_focus] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_active] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_columns] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_rows] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_gap] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_height] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_width] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_surface] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_background] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_theme] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_padding] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_margin] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_radius] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_border] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_shadow] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_place] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_in] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_col] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_span] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_lift] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_glow] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_brighten] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_dim] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_blur] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_press] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_ring] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_smooth] = {
    .visible = true,
    .named = false,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym__newline] = {
    .visible = false,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_block] = {
    .visible = true,
    .named = true,
  },
  [sym_state_block] = {
    .visible = true,
    .named = true,
  },
  [sym_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_declaration_name] = {
    .visible = true,
    .named = true,
  },
  [sym_declaration_keyword] = {
    .visible = true,
    .named = true,
  },
  [sym_state_keyword] = {
    .visible = true,
    .named = true,
  },
  [sym_property_keyword] = {
    .visible = true,
    .named = true,
  },
  [sym_effect_keyword] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_block_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_statement_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_kind = 1,
  field_name = 2,
  field_property = 3,
  field_value = 4,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_kind] = "kind",
  [field_name] = "name",
  [field_property] = "property",
  [field_value] = "value",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 2},
  [2] = {.index = 2, .length = 1},
  [3] = {.index = 3, .length = 1},
  [4] = {.index = 4, .length = 1},
  [5] = {.index = 5, .length = 2},
  [6] = {.index = 7, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_kind, 0},
    {field_name, 1},
  [2] =
    {field_value, 0},
  [3] =
    {field_property, 0},
  [4] =
    {field_name, 0},
  [5] =
    {field_property, 0},
    {field_value, 1, .inherited = true},
  [7] =
    {field_value, 0, .inherited = true},
    {field_value, 1, .inherited = true},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 2,
  [6] = 4,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 10,
  [15] = 15,
  [16] = 7,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(3);
      if (lookahead == '\n') ADVANCE(8);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == '/') ADVANCE(2);
      if (lookahead == '{') ADVANCE(4);
      if (lookahead == '}') ADVANCE(5);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(0);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(6);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(8);
      END_STATE();
    case 2:
      if (lookahead == '/') ADVANCE(7);
      END_STATE();
    case 3:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 4:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 5:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(6);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(7);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(sym__newline);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      ADVANCE_MAP(
        'a', 1,
        'b', 2,
        'c', 3,
        'd', 4,
        'f', 5,
        'g', 6,
        'h', 7,
        'i', 8,
        'l', 9,
        'm', 10,
        'p', 11,
        'r', 12,
        's', 13,
        't', 14,
        'w', 15,
      );
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == 'c') ADVANCE(16);
      if (lookahead == 'r') ADVANCE(17);
      END_STATE();
    case 2:
      if (lookahead == 'a') ADVANCE(18);
      if (lookahead == 'l') ADVANCE(19);
      if (lookahead == 'o') ADVANCE(20);
      if (lookahead == 'r') ADVANCE(21);
      if (lookahead == 'u') ADVANCE(22);
      END_STATE();
    case 3:
      if (lookahead == 'a') ADVANCE(23);
      if (lookahead == 'o') ADVANCE(24);
      END_STATE();
    case 4:
      if (lookahead == 'i') ADVANCE(25);
      END_STATE();
    case 5:
      if (lookahead == 'o') ADVANCE(26);
      END_STATE();
    case 6:
      if (lookahead == 'a') ADVANCE(27);
      if (lookahead == 'l') ADVANCE(28);
      if (lookahead == 'r') ADVANCE(29);
      END_STATE();
    case 7:
      if (lookahead == 'e') ADVANCE(30);
      if (lookahead == 'o') ADVANCE(31);
      END_STATE();
    case 8:
      if (lookahead == 'n') ADVANCE(32);
      END_STATE();
    case 9:
      if (lookahead == 'i') ADVANCE(33);
      END_STATE();
    case 10:
      if (lookahead == 'a') ADVANCE(34);
      END_STATE();
    case 11:
      if (lookahead == 'a') ADVANCE(35);
      if (lookahead == 'l') ADVANCE(36);
      if (lookahead == 'r') ADVANCE(37);
      END_STATE();
    case 12:
      if (lookahead == 'a') ADVANCE(38);
      if (lookahead == 'i') ADVANCE(39);
      if (lookahead == 'o') ADVANCE(40);
      END_STATE();
    case 13:
      if (lookahead == 'h') ADVANCE(41);
      if (lookahead == 'm') ADVANCE(42);
      if (lookahead == 'p') ADVANCE(43);
      if (lookahead == 't') ADVANCE(44);
      if (lookahead == 'u') ADVANCE(45);
      END_STATE();
    case 14:
      if (lookahead == 'e') ADVANCE(46);
      if (lookahead == 'h') ADVANCE(47);
      if (lookahead == 'o') ADVANCE(48);
      END_STATE();
    case 15:
      if (lookahead == 'i') ADVANCE(49);
      END_STATE();
    case 16:
      if (lookahead == 't') ADVANCE(50);
      END_STATE();
    case 17:
      if (lookahead == 'e') ADVANCE(51);
      END_STATE();
    case 18:
      if (lookahead == 'c') ADVANCE(52);
      END_STATE();
    case 19:
      if (lookahead == 'u') ADVANCE(53);
      END_STATE();
    case 20:
      if (lookahead == 'r') ADVANCE(54);
      END_STATE();
    case 21:
      if (lookahead == 'i') ADVANCE(55);
      END_STATE();
    case 22:
      if (lookahead == 't') ADVANCE(56);
      END_STATE();
    case 23:
      if (lookahead == 'r') ADVANCE(57);
      END_STATE();
    case 24:
      if (lookahead == 'l') ADVANCE(58);
      END_STATE();
    case 25:
      if (lookahead == 'm') ADVANCE(59);
      END_STATE();
    case 26:
      if (lookahead == 'c') ADVANCE(60);
      END_STATE();
    case 27:
      if (lookahead == 'p') ADVANCE(61);
      END_STATE();
    case 28:
      if (lookahead == 'o') ADVANCE(62);
      END_STATE();
    case 29:
      if (lookahead == 'i') ADVANCE(63);
      END_STATE();
    case 30:
      if (lookahead == 'i') ADVANCE(64);
      END_STATE();
    case 31:
      if (lookahead == 'v') ADVANCE(65);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_in);
      END_STATE();
    case 33:
      if (lookahead == 'f') ADVANCE(66);
      END_STATE();
    case 34:
      if (lookahead == 'r') ADVANCE(67);
      END_STATE();
    case 35:
      if (lookahead == 'd') ADVANCE(68);
      END_STATE();
    case 36:
      if (lookahead == 'a') ADVANCE(69);
      END_STATE();
    case 37:
      if (lookahead == 'e') ADVANCE(70);
      END_STATE();
    case 38:
      if (lookahead == 'd') ADVANCE(71);
      END_STATE();
    case 39:
      if (lookahead == 'n') ADVANCE(72);
      END_STATE();
    case 40:
      if (lookahead == 'w') ADVANCE(73);
      END_STATE();
    case 41:
      if (lookahead == 'a') ADVANCE(74);
      END_STATE();
    case 42:
      if (lookahead == 'o') ADVANCE(75);
      END_STATE();
    case 43:
      if (lookahead == 'a') ADVANCE(76);
      END_STATE();
    case 44:
      if (lookahead == 'a') ADVANCE(77);
      END_STATE();
    case 45:
      if (lookahead == 'r') ADVANCE(78);
      END_STATE();
    case 46:
      if (lookahead == 'x') ADVANCE(79);
      END_STATE();
    case 47:
      if (lookahead == 'e') ADVANCE(80);
      END_STATE();
    case 48:
      if (lookahead == 'k') ADVANCE(81);
      END_STATE();
    case 49:
      if (lookahead == 'd') ADVANCE(82);
      END_STATE();
    case 50:
      if (lookahead == 'i') ADVANCE(83);
      END_STATE();
    case 51:
      if (lookahead == 'a') ADVANCE(84);
      END_STATE();
    case 52:
      if (lookahead == 'k') ADVANCE(85);
      END_STATE();
    case 53:
      if (lookahead == 'r') ADVANCE(86);
      END_STATE();
    case 54:
      if (lookahead == 'd') ADVANCE(87);
      END_STATE();
    case 55:
      if (lookahead == 'g') ADVANCE(88);
      END_STATE();
    case 56:
      if (lookahead == 't') ADVANCE(89);
      END_STATE();
    case 57:
      if (lookahead == 'd') ADVANCE(90);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(anon_sym_col);
      if (lookahead == 'u') ADVANCE(91);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(anon_sym_dim);
      END_STATE();
    case 60:
      if (lookahead == 'u') ADVANCE(92);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(anon_sym_gap);
      END_STATE();
    case 62:
      if (lookahead == 'w') ADVANCE(93);
      END_STATE();
    case 63:
      if (lookahead == 'd') ADVANCE(94);
      END_STATE();
    case 64:
      if (lookahead == 'g') ADVANCE(95);
      END_STATE();
    case 65:
      if (lookahead == 'e') ADVANCE(96);
      END_STATE();
    case 66:
      if (lookahead == 't') ADVANCE(97);
      END_STATE();
    case 67:
      if (lookahead == 'g') ADVANCE(98);
      END_STATE();
    case 68:
      if (lookahead == 'd') ADVANCE(99);
      END_STATE();
    case 69:
      if (lookahead == 'c') ADVANCE(100);
      END_STATE();
    case 70:
      if (lookahead == 's') ADVANCE(101);
      END_STATE();
    case 71:
      if (lookahead == 'i') ADVANCE(102);
      END_STATE();
    case 72:
      if (lookahead == 'g') ADVANCE(103);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(anon_sym_row);
      if (lookahead == 's') ADVANCE(104);
      END_STATE();
    case 74:
      if (lookahead == 'd') ADVANCE(105);
      END_STATE();
    case 75:
      if (lookahead == 'o') ADVANCE(106);
      END_STATE();
    case 76:
      if (lookahead == 'n') ADVANCE(107);
      END_STATE();
    case 77:
      if (lookahead == 'c') ADVANCE(108);
      END_STATE();
    case 78:
      if (lookahead == 'f') ADVANCE(109);
      END_STATE();
    case 79:
      if (lookahead == 't') ADVANCE(110);
      END_STATE();
    case 80:
      if (lookahead == 'm') ADVANCE(111);
      END_STATE();
    case 81:
      if (lookahead == 'e') ADVANCE(112);
      END_STATE();
    case 82:
      if (lookahead == 't') ADVANCE(113);
      END_STATE();
    case 83:
      if (lookahead == 'v') ADVANCE(114);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(anon_sym_area);
      END_STATE();
    case 85:
      if (lookahead == 'g') ADVANCE(115);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(anon_sym_blur);
      END_STATE();
    case 87:
      if (lookahead == 'e') ADVANCE(116);
      END_STATE();
    case 88:
      if (lookahead == 'h') ADVANCE(117);
      END_STATE();
    case 89:
      if (lookahead == 'o') ADVANCE(118);
      END_STATE();
    case 90:
      ACCEPT_TOKEN(anon_sym_card);
      END_STATE();
    case 91:
      if (lookahead == 'm') ADVANCE(119);
      END_STATE();
    case 92:
      if (lookahead == 's') ADVANCE(120);
      END_STATE();
    case 93:
      ACCEPT_TOKEN(anon_sym_glow);
      END_STATE();
    case 94:
      ACCEPT_TOKEN(anon_sym_grid);
      END_STATE();
    case 95:
      if (lookahead == 'h') ADVANCE(121);
      END_STATE();
    case 96:
      if (lookahead == 'r') ADVANCE(122);
      END_STATE();
    case 97:
      ACCEPT_TOKEN(anon_sym_lift);
      END_STATE();
    case 98:
      if (lookahead == 'i') ADVANCE(123);
      END_STATE();
    case 99:
      if (lookahead == 'i') ADVANCE(124);
      END_STATE();
    case 100:
      if (lookahead == 'e') ADVANCE(125);
      END_STATE();
    case 101:
      if (lookahead == 's') ADVANCE(126);
      END_STATE();
    case 102:
      if (lookahead == 'u') ADVANCE(127);
      END_STATE();
    case 103:
      ACCEPT_TOKEN(anon_sym_ring);
      END_STATE();
    case 104:
      ACCEPT_TOKEN(anon_sym_rows);
      END_STATE();
    case 105:
      if (lookahead == 'o') ADVANCE(128);
      END_STATE();
    case 106:
      if (lookahead == 't') ADVANCE(129);
      END_STATE();
    case 107:
      ACCEPT_TOKEN(anon_sym_span);
      END_STATE();
    case 108:
      if (lookahead == 'k') ADVANCE(130);
      END_STATE();
    case 109:
      if (lookahead == 'a') ADVANCE(131);
      END_STATE();
    case 110:
      ACCEPT_TOKEN(anon_sym_text);
      END_STATE();
    case 111:
      if (lookahead == 'e') ADVANCE(132);
      END_STATE();
    case 112:
      if (lookahead == 'n') ADVANCE(133);
      END_STATE();
    case 113:
      if (lookahead == 'h') ADVANCE(134);
      END_STATE();
    case 114:
      if (lookahead == 'e') ADVANCE(135);
      END_STATE();
    case 115:
      if (lookahead == 'r') ADVANCE(136);
      END_STATE();
    case 116:
      if (lookahead == 'r') ADVANCE(137);
      END_STATE();
    case 117:
      if (lookahead == 't') ADVANCE(138);
      END_STATE();
    case 118:
      if (lookahead == 'n') ADVANCE(139);
      END_STATE();
    case 119:
      if (lookahead == 'n') ADVANCE(140);
      END_STATE();
    case 120:
      ACCEPT_TOKEN(anon_sym_focus);
      END_STATE();
    case 121:
      if (lookahead == 't') ADVANCE(141);
      END_STATE();
    case 122:
      ACCEPT_TOKEN(anon_sym_hover);
      END_STATE();
    case 123:
      if (lookahead == 'n') ADVANCE(142);
      END_STATE();
    case 124:
      if (lookahead == 'n') ADVANCE(143);
      END_STATE();
    case 125:
      ACCEPT_TOKEN(anon_sym_place);
      END_STATE();
    case 126:
      ACCEPT_TOKEN(anon_sym_press);
      END_STATE();
    case 127:
      if (lookahead == 's') ADVANCE(144);
      END_STATE();
    case 128:
      if (lookahead == 'w') ADVANCE(145);
      END_STATE();
    case 129:
      if (lookahead == 'h') ADVANCE(146);
      END_STATE();
    case 130:
      ACCEPT_TOKEN(anon_sym_stack);
      END_STATE();
    case 131:
      if (lookahead == 'c') ADVANCE(147);
      END_STATE();
    case 132:
      ACCEPT_TOKEN(anon_sym_theme);
      END_STATE();
    case 133:
      if (lookahead == 's') ADVANCE(148);
      END_STATE();
    case 134:
      ACCEPT_TOKEN(anon_sym_width);
      END_STATE();
    case 135:
      ACCEPT_TOKEN(anon_sym_active);
      END_STATE();
    case 136:
      if (lookahead == 'o') ADVANCE(149);
      END_STATE();
    case 137:
      ACCEPT_TOKEN(anon_sym_border);
      END_STATE();
    case 138:
      if (lookahead == 'e') ADVANCE(150);
      END_STATE();
    case 139:
      ACCEPT_TOKEN(anon_sym_button);
      END_STATE();
    case 140:
      if (lookahead == 's') ADVANCE(151);
      END_STATE();
    case 141:
      ACCEPT_TOKEN(anon_sym_height);
      END_STATE();
    case 142:
      ACCEPT_TOKEN(anon_sym_margin);
      END_STATE();
    case 143:
      if (lookahead == 'g') ADVANCE(152);
      END_STATE();
    case 144:
      ACCEPT_TOKEN(anon_sym_radius);
      END_STATE();
    case 145:
      ACCEPT_TOKEN(anon_sym_shadow);
      END_STATE();
    case 146:
      ACCEPT_TOKEN(anon_sym_smooth);
      END_STATE();
    case 147:
      if (lookahead == 'e') ADVANCE(153);
      END_STATE();
    case 148:
      ACCEPT_TOKEN(anon_sym_tokens);
      END_STATE();
    case 149:
      if (lookahead == 'u') ADVANCE(154);
      END_STATE();
    case 150:
      if (lookahead == 'n') ADVANCE(155);
      END_STATE();
    case 151:
      ACCEPT_TOKEN(anon_sym_columns);
      END_STATE();
    case 152:
      ACCEPT_TOKEN(anon_sym_padding);
      END_STATE();
    case 153:
      ACCEPT_TOKEN(anon_sym_surface);
      END_STATE();
    case 154:
      if (lookahead == 'n') ADVANCE(156);
      END_STATE();
    case 155:
      ACCEPT_TOKEN(anon_sym_brighten);
      END_STATE();
    case 156:
      if (lookahead == 'd') ADVANCE(157);
      END_STATE();
    case 157:
      ACCEPT_TOKEN(anon_sym_background);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_tokens] = ACTIONS(1),
    [anon_sym_grid] = ACTIONS(1),
    [anon_sym_area] = ACTIONS(1),
    [anon_sym_card] = ACTIONS(1),
    [anon_sym_stack] = ACTIONS(1),
    [anon_sym_row] = ACTIONS(1),
    [anon_sym_button] = ACTIONS(1),
    [anon_sym_text] = ACTIONS(1),
    [anon_sym_hover] = ACTIONS(1),
    [anon_sym_focus] = ACTIONS(1),
    [anon_sym_active] = ACTIONS(1),
    [anon_sym_columns] = ACTIONS(1),
    [anon_sym_rows] = ACTIONS(1),
    [anon_sym_gap] = ACTIONS(1),
    [anon_sym_height] = ACTIONS(1),
    [anon_sym_width] = ACTIONS(1),
    [anon_sym_surface] = ACTIONS(1),
    [anon_sym_background] = ACTIONS(1),
    [anon_sym_theme] = ACTIONS(1),
    [anon_sym_padding] = ACTIONS(1),
    [anon_sym_margin] = ACTIONS(1),
    [anon_sym_radius] = ACTIONS(1),
    [anon_sym_border] = ACTIONS(1),
    [anon_sym_shadow] = ACTIONS(1),
    [anon_sym_place] = ACTIONS(1),
    [anon_sym_in] = ACTIONS(1),
    [anon_sym_col] = ACTIONS(1),
    [anon_sym_span] = ACTIONS(1),
    [anon_sym_lift] = ACTIONS(1),
    [anon_sym_glow] = ACTIONS(1),
    [anon_sym_brighten] = ACTIONS(1),
    [anon_sym_dim] = ACTIONS(1),
    [anon_sym_blur] = ACTIONS(1),
    [anon_sym_press] = ACTIONS(1),
    [anon_sym_ring] = ACTIONS(1),
    [anon_sym_smooth] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
    [sym__newline] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(27),
    [sym_declaration] = STATE(13),
    [sym_declaration_keyword] = STATE(21),
    [aux_sym_source_file_repeat1] = STATE(13),
    [ts_builtin_sym_end] = ACTIONS(5),
    [anon_sym_tokens] = ACTIONS(7),
    [anon_sym_grid] = ACTIONS(7),
    [anon_sym_area] = ACTIONS(7),
    [anon_sym_card] = ACTIONS(7),
    [anon_sym_stack] = ACTIONS(7),
    [anon_sym_row] = ACTIONS(7),
    [anon_sym_button] = ACTIONS(7),
    [anon_sym_text] = ACTIONS(7),
    [sym_comment] = ACTIONS(3),
    [sym__newline] = ACTIONS(9),
  },
  [STATE(2)] = {
    [sym_state_block] = STATE(4),
    [sym_statement] = STATE(4),
    [sym_state_keyword] = STATE(25),
    [sym_property_keyword] = STATE(18),
    [sym_effect_keyword] = STATE(18),
    [aux_sym_block_repeat1] = STATE(4),
    [sym_identifier] = ACTIONS(11),
    [anon_sym_RBRACE] = ACTIONS(13),
    [anon_sym_row] = ACTIONS(15),
    [anon_sym_hover] = ACTIONS(17),
    [anon_sym_focus] = ACTIONS(17),
    [anon_sym_active] = ACTIONS(17),
    [anon_sym_columns] = ACTIONS(15),
    [anon_sym_rows] = ACTIONS(15),
    [anon_sym_gap] = ACTIONS(15),
    [anon_sym_height] = ACTIONS(15),
    [anon_sym_width] = ACTIONS(15),
    [anon_sym_surface] = ACTIONS(15),
    [anon_sym_background] = ACTIONS(15),
    [anon_sym_theme] = ACTIONS(15),
    [anon_sym_padding] = ACTIONS(15),
    [anon_sym_margin] = ACTIONS(15),
    [anon_sym_radius] = ACTIONS(15),
    [anon_sym_border] = ACTIONS(15),
    [anon_sym_shadow] = ACTIONS(15),
    [anon_sym_place] = ACTIONS(15),
    [anon_sym_in] = ACTIONS(15),
    [anon_sym_col] = ACTIONS(15),
    [anon_sym_span] = ACTIONS(15),
    [anon_sym_lift] = ACTIONS(19),
    [anon_sym_glow] = ACTIONS(19),
    [anon_sym_brighten] = ACTIONS(19),
    [anon_sym_dim] = ACTIONS(19),
    [anon_sym_blur] = ACTIONS(19),
    [anon_sym_press] = ACTIONS(19),
    [anon_sym_ring] = ACTIONS(19),
    [anon_sym_smooth] = ACTIONS(19),
    [sym_comment] = ACTIONS(3),
    [sym__newline] = ACTIONS(21),
  },
  [STATE(3)] = {
    [sym_state_block] = STATE(3),
    [sym_statement] = STATE(3),
    [sym_state_keyword] = STATE(25),
    [sym_property_keyword] = STATE(18),
    [sym_effect_keyword] = STATE(18),
    [aux_sym_block_repeat1] = STATE(3),
    [sym_identifier] = ACTIONS(23),
    [anon_sym_RBRACE] = ACTIONS(26),
    [anon_sym_row] = ACTIONS(28),
    [anon_sym_hover] = ACTIONS(31),
    [anon_sym_focus] = ACTIONS(31),
    [anon_sym_active] = ACTIONS(31),
    [anon_sym_columns] = ACTIONS(28),
    [anon_sym_rows] = ACTIONS(28),
    [anon_sym_gap] = ACTIONS(28),
    [anon_sym_height] = ACTIONS(28),
    [anon_sym_width] = ACTIONS(28),
    [anon_sym_surface] = ACTIONS(28),
    [anon_sym_background] = ACTIONS(28),
    [anon_sym_theme] = ACTIONS(28),
    [anon_sym_padding] = ACTIONS(28),
    [anon_sym_margin] = ACTIONS(28),
    [anon_sym_radius] = ACTIONS(28),
    [anon_sym_border] = ACTIONS(28),
    [anon_sym_shadow] = ACTIONS(28),
    [anon_sym_place] = ACTIONS(28),
    [anon_sym_in] = ACTIONS(28),
    [anon_sym_col] = ACTIONS(28),
    [anon_sym_span] = ACTIONS(28),
    [anon_sym_lift] = ACTIONS(34),
    [anon_sym_glow] = ACTIONS(34),
    [anon_sym_brighten] = ACTIONS(34),
    [anon_sym_dim] = ACTIONS(34),
    [anon_sym_blur] = ACTIONS(34),
    [anon_sym_press] = ACTIONS(34),
    [anon_sym_ring] = ACTIONS(34),
    [anon_sym_smooth] = ACTIONS(34),
    [sym_comment] = ACTIONS(3),
    [sym__newline] = ACTIONS(37),
  },
  [STATE(4)] = {
    [sym_state_block] = STATE(3),
    [sym_statement] = STATE(3),
    [sym_state_keyword] = STATE(25),
    [sym_property_keyword] = STATE(18),
    [sym_effect_keyword] = STATE(18),
    [aux_sym_block_repeat1] = STATE(3),
    [sym_identifier] = ACTIONS(11),
    [anon_sym_RBRACE] = ACTIONS(40),
    [anon_sym_row] = ACTIONS(15),
    [anon_sym_hover] = ACTIONS(17),
    [anon_sym_focus] = ACTIONS(17),
    [anon_sym_active] = ACTIONS(17),
    [anon_sym_columns] = ACTIONS(15),
    [anon_sym_rows] = ACTIONS(15),
    [anon_sym_gap] = ACTIONS(15),
    [anon_sym_height] = ACTIONS(15),
    [anon_sym_width] = ACTIONS(15),
    [anon_sym_surface] = ACTIONS(15),
    [anon_sym_background] = ACTIONS(15),
    [anon_sym_theme] = ACTIONS(15),
    [anon_sym_padding] = ACTIONS(15),
    [anon_sym_margin] = ACTIONS(15),
    [anon_sym_radius] = ACTIONS(15),
    [anon_sym_border] = ACTIONS(15),
    [anon_sym_shadow] = ACTIONS(15),
    [anon_sym_place] = ACTIONS(15),
    [anon_sym_in] = ACTIONS(15),
    [anon_sym_col] = ACTIONS(15),
    [anon_sym_span] = ACTIONS(15),
    [anon_sym_lift] = ACTIONS(19),
    [anon_sym_glow] = ACTIONS(19),
    [anon_sym_brighten] = ACTIONS(19),
    [anon_sym_dim] = ACTIONS(19),
    [anon_sym_blur] = ACTIONS(19),
    [anon_sym_press] = ACTIONS(19),
    [anon_sym_ring] = ACTIONS(19),
    [anon_sym_smooth] = ACTIONS(19),
    [sym_comment] = ACTIONS(3),
    [sym__newline] = ACTIONS(42),
  },
  [STATE(5)] = {
    [sym_state_block] = STATE(6),
    [sym_statement] = STATE(6),
    [sym_state_keyword] = STATE(25),
    [sym_property_keyword] = STATE(18),
    [sym_effect_keyword] = STATE(18),
    [aux_sym_block_repeat1] = STATE(6),
    [sym_identifier] = ACTIONS(11),
    [anon_sym_RBRACE] = ACTIONS(44),
    [anon_sym_row] = ACTIONS(15),
    [anon_sym_hover] = ACTIONS(17),
    [anon_sym_focus] = ACTIONS(17),
    [anon_sym_active] = ACTIONS(17),
    [anon_sym_columns] = ACTIONS(15),
    [anon_sym_rows] = ACTIONS(15),
    [anon_sym_gap] = ACTIONS(15),
    [anon_sym_height] = ACTIONS(15),
    [anon_sym_width] = ACTIONS(15),
    [anon_sym_surface] = ACTIONS(15),
    [anon_sym_background] = ACTIONS(15),
    [anon_sym_theme] = ACTIONS(15),
    [anon_sym_padding] = ACTIONS(15),
    [anon_sym_margin] = ACTIONS(15),
    [anon_sym_radius] = ACTIONS(15),
    [anon_sym_border] = ACTIONS(15),
    [anon_sym_shadow] = ACTIONS(15),
    [anon_sym_place] = ACTIONS(15),
    [anon_sym_in] = ACTIONS(15),
    [anon_sym_col] = ACTIONS(15),
    [anon_sym_span] = ACTIONS(15),
    [anon_sym_lift] = ACTIONS(19),
    [anon_sym_glow] = ACTIONS(19),
    [anon_sym_brighten] = ACTIONS(19),
    [anon_sym_dim] = ACTIONS(19),
    [anon_sym_blur] = ACTIONS(19),
    [anon_sym_press] = ACTIONS(19),
    [anon_sym_ring] = ACTIONS(19),
    [anon_sym_smooth] = ACTIONS(19),
    [sym_comment] = ACTIONS(3),
    [sym__newline] = ACTIONS(46),
  },
  [STATE(6)] = {
    [sym_state_block] = STATE(3),
    [sym_statement] = STATE(3),
    [sym_state_keyword] = STATE(25),
    [sym_property_keyword] = STATE(18),
    [sym_effect_keyword] = STATE(18),
    [aux_sym_block_repeat1] = STATE(3),
    [sym_identifier] = ACTIONS(11),
    [anon_sym_RBRACE] = ACTIONS(48),
    [anon_sym_row] = ACTIONS(15),
    [anon_sym_hover] = ACTIONS(17),
    [anon_sym_focus] = ACTIONS(17),
    [anon_sym_active] = ACTIONS(17),
    [anon_sym_columns] = ACTIONS(15),
    [anon_sym_rows] = ACTIONS(15),
    [anon_sym_gap] = ACTIONS(15),
    [anon_sym_height] = ACTIONS(15),
    [anon_sym_width] = ACTIONS(15),
    [anon_sym_surface] = ACTIONS(15),
    [anon_sym_background] = ACTIONS(15),
    [anon_sym_theme] = ACTIONS(15),
    [anon_sym_padding] = ACTIONS(15),
    [anon_sym_margin] = ACTIONS(15),
    [anon_sym_radius] = ACTIONS(15),
    [anon_sym_border] = ACTIONS(15),
    [anon_sym_shadow] = ACTIONS(15),
    [anon_sym_place] = ACTIONS(15),
    [anon_sym_in] = ACTIONS(15),
    [anon_sym_col] = ACTIONS(15),
    [anon_sym_span] = ACTIONS(15),
    [anon_sym_lift] = ACTIONS(19),
    [anon_sym_glow] = ACTIONS(19),
    [anon_sym_brighten] = ACTIONS(19),
    [anon_sym_dim] = ACTIONS(19),
    [anon_sym_blur] = ACTIONS(19),
    [anon_sym_press] = ACTIONS(19),
    [anon_sym_ring] = ACTIONS(19),
    [anon_sym_smooth] = ACTIONS(19),
    [sym_comment] = ACTIONS(3),
    [sym__newline] = ACTIONS(42),
  },
  [STATE(7)] = {
    [sym_identifier] = ACTIONS(50),
    [anon_sym_RBRACE] = ACTIONS(52),
    [anon_sym_row] = ACTIONS(50),
    [anon_sym_hover] = ACTIONS(50),
    [anon_sym_focus] = ACTIONS(50),
    [anon_sym_active] = ACTIONS(50),
    [anon_sym_columns] = ACTIONS(50),
    [anon_sym_rows] = ACTIONS(50),
    [anon_sym_gap] = ACTIONS(50),
    [anon_sym_height] = ACTIONS(50),
    [anon_sym_width] = ACTIONS(50),
    [anon_sym_surface] = ACTIONS(50),
    [anon_sym_background] = ACTIONS(50),
    [anon_sym_theme] = ACTIONS(50),
    [anon_sym_padding] = ACTIONS(50),
    [anon_sym_margin] = ACTIONS(50),
    [anon_sym_radius] = ACTIONS(50),
    [anon_sym_border] = ACTIONS(50),
    [anon_sym_shadow] = ACTIONS(50),
    [anon_sym_place] = ACTIONS(50),
    [anon_sym_in] = ACTIONS(50),
    [anon_sym_col] = ACTIONS(50),
    [anon_sym_span] = ACTIONS(50),
    [anon_sym_lift] = ACTIONS(50),
    [anon_sym_glow] = ACTIONS(50),
    [anon_sym_brighten] = ACTIONS(50),
    [anon_sym_dim] = ACTIONS(50),
    [anon_sym_blur] = ACTIONS(50),
    [anon_sym_press] = ACTIONS(50),
    [anon_sym_ring] = ACTIONS(50),
    [anon_sym_smooth] = ACTIONS(50),
    [sym_comment] = ACTIONS(3),
    [sym__newline] = ACTIONS(52),
  },
  [STATE(8)] = {
    [sym_identifier] = ACTIONS(54),
    [anon_sym_RBRACE] = ACTIONS(56),
    [anon_sym_row] = ACTIONS(54),
    [anon_sym_hover] = ACTIONS(54),
    [anon_sym_focus] = ACTIONS(54),
    [anon_sym_active] = ACTIONS(54),
    [anon_sym_columns] = ACTIONS(54),
    [anon_sym_rows] = ACTIONS(54),
    [anon_sym_gap] = ACTIONS(54),
    [anon_sym_height] = ACTIONS(54),
    [anon_sym_width] = ACTIONS(54),
    [anon_sym_surface] = ACTIONS(54),
    [anon_sym_background] = ACTIONS(54),
    [anon_sym_theme] = ACTIONS(54),
    [anon_sym_padding] = ACTIONS(54),
    [anon_sym_margin] = ACTIONS(54),
    [anon_sym_radius] = ACTIONS(54),
    [anon_sym_border] = ACTIONS(54),
    [anon_sym_shadow] = ACTIONS(54),
    [anon_sym_place] = ACTIONS(54),
    [anon_sym_in] = ACTIONS(54),
    [anon_sym_col] = ACTIONS(54),
    [anon_sym_span] = ACTIONS(54),
    [anon_sym_lift] = ACTIONS(54),
    [anon_sym_glow] = ACTIONS(54),
    [anon_sym_brighten] = ACTIONS(54),
    [anon_sym_dim] = ACTIONS(54),
    [anon_sym_blur] = ACTIONS(54),
    [anon_sym_press] = ACTIONS(54),
    [anon_sym_ring] = ACTIONS(54),
    [anon_sym_smooth] = ACTIONS(54),
    [sym_comment] = ACTIONS(3),
    [sym__newline] = ACTIONS(56),
  },
  [STATE(9)] = {
    [sym_identifier] = ACTIONS(58),
    [anon_sym_RBRACE] = ACTIONS(60),
    [anon_sym_row] = ACTIONS(58),
    [anon_sym_hover] = ACTIONS(58),
    [anon_sym_focus] = ACTIONS(58),
    [anon_sym_active] = ACTIONS(58),
    [anon_sym_columns] = ACTIONS(58),
    [anon_sym_rows] = ACTIONS(58),
    [anon_sym_gap] = ACTIONS(58),
    [anon_sym_height] = ACTIONS(58),
    [anon_sym_width] = ACTIONS(58),
    [anon_sym_surface] = ACTIONS(58),
    [anon_sym_background] = ACTIONS(58),
    [anon_sym_theme] = ACTIONS(58),
    [anon_sym_padding] = ACTIONS(58),
    [anon_sym_margin] = ACTIONS(58),
    [anon_sym_radius] = ACTIONS(58),
    [anon_sym_border] = ACTIONS(58),
    [anon_sym_shadow] = ACTIONS(58),
    [anon_sym_place] = ACTIONS(58),
    [anon_sym_in] = ACTIONS(58),
    [anon_sym_col] = ACTIONS(58),
    [anon_sym_span] = ACTIONS(58),
    [anon_sym_lift] = ACTIONS(58),
    [anon_sym_glow] = ACTIONS(58),
    [anon_sym_brighten] = ACTIONS(58),
    [anon_sym_dim] = ACTIONS(58),
    [anon_sym_blur] = ACTIONS(58),
    [anon_sym_press] = ACTIONS(58),
    [anon_sym_ring] = ACTIONS(58),
    [anon_sym_smooth] = ACTIONS(58),
    [sym_comment] = ACTIONS(3),
    [sym__newline] = ACTIONS(60),
  },
  [STATE(10)] = {
    [sym_identifier] = ACTIONS(62),
    [anon_sym_RBRACE] = ACTIONS(64),
    [anon_sym_row] = ACTIONS(62),
    [anon_sym_hover] = ACTIONS(62),
    [anon_sym_focus] = ACTIONS(62),
    [anon_sym_active] = ACTIONS(62),
    [anon_sym_columns] = ACTIONS(62),
    [anon_sym_rows] = ACTIONS(62),
    [anon_sym_gap] = ACTIONS(62),
    [anon_sym_height] = ACTIONS(62),
    [anon_sym_width] = ACTIONS(62),
    [anon_sym_surface] = ACTIONS(62),
    [anon_sym_background] = ACTIONS(62),
    [anon_sym_theme] = ACTIONS(62),
    [anon_sym_padding] = ACTIONS(62),
    [anon_sym_margin] = ACTIONS(62),
    [anon_sym_radius] = ACTIONS(62),
    [anon_sym_border] = ACTIONS(62),
    [anon_sym_shadow] = ACTIONS(62),
    [anon_sym_place] = ACTIONS(62),
    [anon_sym_in] = ACTIONS(62),
    [anon_sym_col] = ACTIONS(62),
    [anon_sym_span] = ACTIONS(62),
    [anon_sym_lift] = ACTIONS(62),
    [anon_sym_glow] = ACTIONS(62),
    [anon_sym_brighten] = ACTIONS(62),
    [anon_sym_dim] = ACTIONS(62),
    [anon_sym_blur] = ACTIONS(62),
    [anon_sym_press] = ACTIONS(62),
    [anon_sym_ring] = ACTIONS(62),
    [anon_sym_smooth] = ACTIONS(62),
    [sym_comment] = ACTIONS(3),
    [sym__newline] = ACTIONS(64),
  },
  [STATE(11)] = {
    [sym_identifier] = ACTIONS(66),
    [anon_sym_RBRACE] = ACTIONS(68),
    [anon_sym_row] = ACTIONS(66),
    [anon_sym_hover] = ACTIONS(66),
    [anon_sym_focus] = ACTIONS(66),
    [anon_sym_active] = ACTIONS(66),
    [anon_sym_columns] = ACTIONS(66),
    [anon_sym_rows] = ACTIONS(66),
    [anon_sym_gap] = ACTIONS(66),
    [anon_sym_height] = ACTIONS(66),
    [anon_sym_width] = ACTIONS(66),
    [anon_sym_surface] = ACTIONS(66),
    [anon_sym_background] = ACTIONS(66),
    [anon_sym_theme] = ACTIONS(66),
    [anon_sym_padding] = ACTIONS(66),
    [anon_sym_margin] = ACTIONS(66),
    [anon_sym_radius] = ACTIONS(66),
    [anon_sym_border] = ACTIONS(66),
    [anon_sym_shadow] = ACTIONS(66),
    [anon_sym_place] = ACTIONS(66),
    [anon_sym_in] = ACTIONS(66),
    [anon_sym_col] = ACTIONS(66),
    [anon_sym_span] = ACTIONS(66),
    [anon_sym_lift] = ACTIONS(66),
    [anon_sym_glow] = ACTIONS(66),
    [anon_sym_brighten] = ACTIONS(66),
    [anon_sym_dim] = ACTIONS(66),
    [anon_sym_blur] = ACTIONS(66),
    [anon_sym_press] = ACTIONS(66),
    [anon_sym_ring] = ACTIONS(66),
    [anon_sym_smooth] = ACTIONS(66),
    [sym_comment] = ACTIONS(3),
    [sym__newline] = ACTIONS(68),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(70), 1,
      ts_builtin_sym_end,
    ACTIONS(75), 1,
      sym__newline,
    STATE(21), 1,
      sym_declaration_keyword,
    STATE(12), 2,
      sym_declaration,
      aux_sym_source_file_repeat1,
    ACTIONS(72), 8,
      anon_sym_tokens,
      anon_sym_grid,
      anon_sym_area,
      anon_sym_card,
      anon_sym_stack,
      anon_sym_row,
      anon_sym_button,
      anon_sym_text,
  [27] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(78), 1,
      ts_builtin_sym_end,
    ACTIONS(80), 1,
      sym__newline,
    STATE(21), 1,
      sym_declaration_keyword,
    STATE(12), 2,
      sym_declaration,
      aux_sym_source_file_repeat1,
    ACTIONS(7), 8,
      anon_sym_tokens,
      anon_sym_grid,
      anon_sym_area,
      anon_sym_card,
      anon_sym_stack,
      anon_sym_row,
      anon_sym_button,
      anon_sym_text,
  [54] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(64), 10,
      ts_builtin_sym_end,
      anon_sym_tokens,
      anon_sym_grid,
      anon_sym_area,
      anon_sym_card,
      anon_sym_stack,
      anon_sym_row,
      anon_sym_button,
      anon_sym_text,
      sym__newline,
  [70] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(82), 10,
      ts_builtin_sym_end,
      anon_sym_tokens,
      anon_sym_grid,
      anon_sym_area,
      anon_sym_card,
      anon_sym_stack,
      anon_sym_row,
      anon_sym_button,
      anon_sym_text,
      sym__newline,
  [86] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(52), 10,
      ts_builtin_sym_end,
      anon_sym_tokens,
      anon_sym_grid,
      anon_sym_area,
      anon_sym_card,
      anon_sym_stack,
      anon_sym_row,
      anon_sym_button,
      anon_sym_text,
      sym__newline,
  [102] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(84), 1,
      sym_identifier,
    ACTIONS(87), 1,
      sym__newline,
    STATE(17), 1,
      aux_sym_statement_repeat1,
  [115] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(89), 1,
      sym_identifier,
    ACTIONS(91), 1,
      sym__newline,
    STATE(19), 1,
      aux_sym_statement_repeat1,
  [128] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(89), 1,
      sym_identifier,
    ACTIONS(93), 1,
      sym__newline,
    STATE(17), 1,
      aux_sym_statement_repeat1,
  [141] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(95), 1,
      anon_sym_LBRACE,
    STATE(15), 1,
      sym_block,
  [151] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(97), 1,
      sym_identifier,
    STATE(20), 1,
      sym_declaration_name,
  [161] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(99), 2,
      sym_identifier,
      sym__newline,
  [169] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(101), 2,
      sym_identifier,
      sym__newline,
  [177] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(103), 2,
      sym_identifier,
      sym__newline,
  [185] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(105), 1,
      anon_sym_LBRACE,
    STATE(8), 1,
      sym_block,
  [195] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(107), 1,
      sym_identifier,
  [202] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(109), 1,
      ts_builtin_sym_end,
  [209] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(111), 1,
      anon_sym_LBRACE,
  [216] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(113), 1,
      anon_sym_LBRACE,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(12)] = 0,
  [SMALL_STATE(13)] = 27,
  [SMALL_STATE(14)] = 54,
  [SMALL_STATE(15)] = 70,
  [SMALL_STATE(16)] = 86,
  [SMALL_STATE(17)] = 102,
  [SMALL_STATE(18)] = 115,
  [SMALL_STATE(19)] = 128,
  [SMALL_STATE(20)] = 141,
  [SMALL_STATE(21)] = 151,
  [SMALL_STATE(22)] = 161,
  [SMALL_STATE(23)] = 169,
  [SMALL_STATE(24)] = 177,
  [SMALL_STATE(25)] = 185,
  [SMALL_STATE(26)] = 195,
  [SMALL_STATE(27)] = 202,
  [SMALL_STATE(28)] = 209,
  [SMALL_STATE(29)] = 216,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(18),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(22),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(29),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(23),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [23] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(18),
  [26] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0),
  [28] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(22),
  [31] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(29),
  [34] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(23),
  [37] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [40] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [42] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [44] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [46] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [48] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [50] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 3, 0, 0),
  [52] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 3, 0, 0),
  [54] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_state_block, 2, 0, 4),
  [56] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_state_block, 2, 0, 4),
  [58] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_statement, 2, 0, 3),
  [60] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_statement, 2, 0, 3),
  [62] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 2, 0, 0),
  [64] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 2, 0, 0),
  [66] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_statement, 3, 0, 5),
  [68] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_statement, 3, 0, 5),
  [70] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [72] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(26),
  [75] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(12),
  [78] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [80] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [82] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_declaration, 3, 0, 1),
  [84] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_statement_repeat1, 2, 0, 6), SHIFT_REPEAT(24),
  [87] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_statement_repeat1, 2, 0, 6),
  [89] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [91] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [93] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [95] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [97] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [99] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_property_keyword, 1, 0, 0),
  [101] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_effect_keyword, 1, 0, 0),
  [103] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_statement_repeat1, 1, 0, 2),
  [105] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [107] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_declaration_keyword, 1, 0, 0),
  [109] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [111] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_declaration_name, 1, 0, 0),
  [113] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_state_keyword, 1, 0, 0),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_frame(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_identifier,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
