//! Token constants — canonical definitions live in `language.rs`.
//!
//! This module re-exports the static slices so existing callers
//! (`frame_lsp`, semantic validators, etc.) keep compiling.

pub use crate::language::{
    ALIGN, ANCHORS, ANIMATIONS, ANIMATION_DIRECTIONS, ANIMATION_FILLS, ANIMATION_PLAY_STATES,
    ANIMATION_PROPERTIES, BORDER_LINE_STYLES, BORDER_STYLES, BOX_SIZING, BREAKPOINTS, COLORS,
    CONTAINERS, CONTROLS, DISPLAY, DURATIONS, EASES, EDGES, EFFECTS, FLEX_DIRECTIONS, FLEX_WRAPS,
    GLOWS, GRADIENT_CORNERS, GRADIENT_TYPES, GRID_FLOWS, HYPHENS, JUSTIFY, KEYFRAME_PROPERTIES,
    LAYOUTS, LETTERS, LINES, MOVEMENT_AMOUNTS, NUDGES, OVERFLOWS, POSITIONS, RADII, SCROLLBARS,
    SCROLL_AXES, SELF_ALIGN, SHADOWS, SIZES, SPACING, SQUARES, SURFACES, TEXT_ALIGN, TEXT_CASES,
    TEXT_DECORATIONS, TEXT_WRAPS, TRACKS, TRANSITIONS, VISIBILITY, VISUAL_AMOUNTS, WHITE_SPACE,
    WORD_BREAKS, Z_LAYERS,
};
